/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hyperxray_an_vpn_HyperVpnService */

#ifndef _Included_com_hyperxray_an_vpn_HyperVpnService
#define _Included_com_hyperxray_an_vpn_HyperVpnService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hyperxray_an_vpn_HyperVpnService
 * Method:    startHyperTunnel
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_hyperxray_an_vpn_HyperVpnService_startHyperTunnel
  (JNIEnv *, jobject, jint, jstring, jstring, jstring, jstring);

/*
 * Class:     com_hyperxray_an_vpn_HyperVpnService
 * Method:    stopHyperTunnel
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_hyperxray_an_vpn_HyperVpnService_stopHyperTunnel
  (JNIEnv *, jobject);

/*
 * Class:     com_hyperxray_an_vpn_HyperVpnService
 * Method:    getTunnelStats
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hyperxray_an_vpn_HyperVpnService_getTunnelStats
  (JNIEnv *, jobject);

/*
 * Class:     com_hyperxray_an_vpn_HyperVpnService
 * Method:    nativeGeneratePublicKey
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hyperxray_an_vpn_HyperVpnService_nativeGeneratePublicKey
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif

