package com.hyperxray.an.common

const val ROUTE_STATS = "stats"
const val ROUTE_CONFIG = "config"
const val ROUTE_LOG = "log"
const val ROUTE_UTILS = "utils"
const val ROUTE_SETTINGS = "settings"
const val ROUTE_MAIN = "main"
const val ROUTE_APP_LIST = "app_list"
const val ROUTE_CONFIG_EDIT = "config_edit"
const val ROUTE_AI_INSIGHTS = "ai_insights"

// Feature module routes (reserved for future implementation)
const val ROUTE_PROFILES = "profiles"
const val ROUTE_VLESS = "vless"
const val ROUTE_REALITY = "reality"
const val ROUTE_HYSTERIA2 = "hysteria2"
const val ROUTE_ROUTING = "routing"
const val ROUTE_POLICY_AI = "policy_ai"
const val ROUTE_TELEGRAM_SETTINGS = "telegram_settings"

// Utils Tool Routes
const val ROUTE_UTILS_WARP = "utils/warp"
const val ROUTE_UTILS_DNS_CACHE = "utils/dns_cache"
const val ROUTE_UTILS_OPTIMIZER = "utils/optimizer"
const val ROUTE_UTILS_IP_INFO = "utils/ip_info"
const val ROUTE_UTILS_PING_TEST = "utils/ping_test"
const val ROUTE_UTILS_GEOIP_LOOKUP = "utils/geoip_lookup"
const val ROUTE_UTILS_NETWORK_INFO = "utils/network_info"
const val ROUTE_UTILS_SPEED_TEST = "utils/speed_test"
const val ROUTE_UTILS_PORT_SCANNER = "utils/port_scanner"
const val ROUTE_UTILS_TRACEROUTE = "utils/traceroute"
const val ROUTE_UTILS_WAKE_ON_LAN = "utils/wake_on_lan"
const val ROUTE_UTILS_SUBNET_CALCULATOR = "utils/subnet_calculator"
const val ROUTE_UTILS_WHOIS_LOOKUP = "utils/whois_lookup"
const val ROUTE_UTILS_DNS_LOOKUP = "utils/dns_lookup"
const val ROUTE_UTILS_SSL_CERT_CHECKER = "utils/ssl_cert_checker"
const val ROUTE_UTILS_HTTP_HEADERS_VIEWER = "utils/http_headers_viewer"
const val ROUTE_UTILS_LAN_SCANNER = "utils/lan_scanner"
const val ROUTE_UTILS_HTTP_CLIENT = "utils/http_client"
const val ROUTE_UTILS_ASN_LOOKUP = "utils/asn_lookup"
const val ROUTE_UTILS_MAC_ADDRESS_LOOKUP = "utils/mac_address_lookup"
const val ROUTE_UTILS_UNIT_CONVERTER = "utils/unit_converter"
const val ROUTE_UTILS_BASE64_CONVERTER = "utils/base64_converter"
const val ROUTE_UTILS_URL_CONVERTER = "utils/url_converter"
const val ROUTE_UTILS_PASSWORD_GENERATOR = "utils/password_generator"

const val NAVIGATION_DEBOUNCE_DELAY = 500L